window.BAROVIA_SHOT_LIST=[
{priority:1,subject:"Village of Barovia — Overview",audience:"Player",purpose:"First impression / geography",shot:"Establishing",lens:"24mm",camera:"ARRI ALEXA 35 / large-format cinematic look",viewpoint:"Hillside overlook at human-accessible height",lighting:"Cold overcast dusk, practical window light",must:"Show the village trapped beneath Ravenloft; church spire, wet roofs, smoke, fog, muddy roads, castle dominating from above.",avoid:"Epic fantasy grandeur, clean streets, bright colour, oversized architecture",site:"Explore hero / Places / player reveal"},
{priority:2,subject:"Village of Barovia — Street",audience:"Both",purpose:"Immersion / daily life",shot:"Street-level",lens:"35mm",camera:"Sony VENICE 2 / naturalistic full-frame cinema",viewpoint:"Eye level walking into the village",lighting:"Blue-grey evening with warm lantern spill",must:"Show mud, timber and stone houses, shuttered windows, woodsmoke, few wary locals, church or Ravenloft glimpsed in distance.",avoid:"Crowded market, cheerful activity, stylised fantasy props",site:"Places / live play"},
{priority:3,subject:"Blood on the Vine Tavern — Exterior",audience:"Both",purpose:"Landmark recognition",shot:"Landmark",lens:"50mm",camera:"Leica SL3 / restrained documentary realism",viewpoint:"Across the street at standing height",lighting:"Wet dusk, warm interior light",must:"Clearly identify a modest village tavern as one of the few warm public interiors in the village.",avoid:"Grand inn, ornate fantasy tavern, bustling city atmosphere",site:"Village of Barovia record"},
{priority:4,subject:"Church of Barovia",audience:"Both",purpose:"Landmark / mood",shot:"Landmark",lens:"50mm",camera:"Hasselblad X2D medium-format look",viewpoint:"Slightly low from churchyard approach",lighting:"Flat cold daylight, weak stained-glass glow",must:"Show damaged but functioning church, graveyard, damp stone, isolation and grief.",avoid:"Cathedral scale, pristine holy architecture, magical radiance",site:"Village of Barovia / Donavich / Doru"},
{priority:5,subject:"Castle Ravenloft — From the Village",audience:"Player",purpose:"Oppression / scale",shot:"Ominous distance",lens:"135mm",camera:"ARRI ALEXA 35 with long cine prime",viewpoint:"Street or rooftop line from the village",lighting:"Mist-heavy dawn or dusk",must:"Compress distance so the castle feels unnaturally close and unavoidable above the settlement.",avoid:"Wide scenic postcard, heroic castle beauty",site:"Explore / Strahd / player handout"},
{priority:6,subject:"Vallaki — Approach to the Gate",audience:"Player",purpose:"Arrival / control",shot:"Approach",lens:"35mm",camera:"Sony VENICE 2",viewpoint:"Road-level approaching the gate",lighting:"Grey afternoon after rain",must:"Show fortified walls, guarded gate, banners, traffic bottleneck, inspection and social control.",avoid:"Huge capital-city scale, empty gate, military spectacle",site:"Vallaki / Places"},
{priority:7,subject:"Vallaki — Town Square",audience:"Both",purpose:"Social tension / usable scene",shot:"Street-level",lens:"35mm",camera:"ARRI ALEXA 35",viewpoint:"Human eye level at edge of square",lighting:"Overcast dusk, brazier and lantern practicals",must:"Show muddy cobbles, market activity, guards, civic banners, statue, ordinary people behaving under observation.",avoid:"Cheerful festival fantasy, pristine civic square, exaggerated crowds",site:"Vallaki / Live Play"},
{priority:8,subject:"Blue Water Inn — Exterior",audience:"Both",purpose:"Safe-ish landmark / social hub",shot:"Landmark",lens:"50mm",camera:"Leica SL3",viewpoint:"Across a narrow street",lighting:"Rainy evening, welcoming windows",must:"Contrast warmth and activity inside with cold oppressive streets outside.",avoid:"Luxury inn, oversized signage, generic fantasy tavern",site:"Vallaki / Martikovs"},
{priority:9,subject:"Tser Pool Encampment",audience:"Player",purpose:"Culture / contrast",shot:"Environmental",lens:"35mm",camera:"Sony VENICE 2",viewpoint:"At camp edge, eye level",lighting:"Blue hour with real firelight and lanterns",must:"Show wagons, horses, family groups, cooking, music, cloth and practical camp life; Ravenloft distant, not dominant.",avoid:"Carnival stereotype, exoticised posing, empty decorative camp",site:"Tser Pool / Vistani"},
{priority:10,subject:"Madam Eva — In Her Tent",audience:"Both",purpose:"NPC identity / encounter",shot:"Environmental portrait",lens:"50mm",camera:"ARRI ALEXA 35 with fast 50mm prime",viewpoint:"Seated eye line across the table",lighting:"Single warm practical source with cool tent-edge spill",must:"Show an elderly powerful reader in a genuinely lived-in tent, cards and objects used rather than staged.",avoid:"Glowing magic effects, theatrical fortune-teller cliché",site:"Madam Eva record"},
{priority:11,subject:"Abbey of Saint Markovia — Approach",audience:"Player",purpose:"Sacred unease / geography",shot:"Approach",lens:"28mm",camera:"Hasselblad X2D medium-format look",viewpoint:"Uphill path toward the abbey",lighting:"Cold morning after rain",must:"Show severe stone abbey above Krezk, grave markers, steep approach, false serenity.",avoid:"Gothic mega-cathedral, obvious horror props, fantasy glow",site:"Krezk / Abbey"},
{priority:12,subject:"Argynvostholt — Ruined Stronghold",audience:"Both",purpose:"History / melancholy",shot:"Establishing",lens:"28mm",camera:"ARRI ALEXA 35",viewpoint:"Road bend revealing the ruin",lighting:"Moonlit cloud break or cold late afternoon",must:"Show a once-noble fortified manor/stronghold now broken, damp and mournful.",avoid:"Impossible floating ruins, enormous cathedral scale",site:"Argynvostholt / Order"},
{priority:13,subject:"Ireena Kolyana — Primary Portrait",audience:"Both",purpose:"Identity / emotional truth",shot:"Character portrait",lens:"85mm",camera:"Sony VENICE 2 with 85mm cine prime",viewpoint:"Eye level, chest-up",lighting:"Soft window light, cool ambient fill",must:"Show a capable young Barovian noblewoman under strain; practical clothing, real skin, tired but steady eyes.",avoid:"Princess glamour, spotless costume, pin-up posing",site:"People / Ireena"},
{priority:14,subject:"Strahd von Zarovich — Formal Portrait",audience:"Both",purpose:"Authority / danger",shot:"Character portrait",lens:"105mm",camera:"Hasselblad X2D / medium-format portrait look",viewpoint:"Eye level, restrained framing",lighting:"Controlled low-key window light, no supernatural glow",must:"Show aristocratic control, age without frailty, immaculate restraint and predatory attention.",avoid:"Monster-face vampire, melodramatic cape pose, red glowing eyes",site:"Strahd / Campaign Brain"},
{priority:15,subject:"Strahd — Seen at Distance",audience:"Player",purpose:"Presence / uncertainty",shot:"Ominous distance",lens:"200mm",camera:"ARRI ALEXA 35 with long telephoto",viewpoint:"Party-eye view across road/ridge/balcony",lighting:"Mist, backlight, low contrast",must:"Make him recognisable enough to disturb but distant enough to create uncertainty.",avoid:"Action pose, obvious combat setup, supernatural visual effects",site:"Live Play / Strahd encounters"}
];